      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install flet==0.21.2

      - name: Prepare Flet Build Config & Android Permissions
        run: |
          cat << 'EOF' > pyproject.toml
          [project]
          name = "carbapp"
          version = "1.0.0"
          description = "Smart Diabetes Management System"
          dependencies = ["flet==0.21.2"]

          [tool.flet]
          org = "com.ibrahim.carbapp"
          product = "حاسبة الكارب الذكية"
          python_version = "3.11"

          [tool.flet.app]
          module = "main"

          [tool.flet.app.boot_screen]
          show = true
          message = "جاري تحضير التطبيق..."

          [tool.flet.app.startup_screen]
          show = true
          message = "جاري تجهيز كل شيء..."

          [tool.flet.android]
          permissions = [
            "camera",
            "read_external_storage",
            "write_external_storage",
            "read_media_images",
            "internet",
            "post_notifications",
            "schedule_exact_alarm",
            "use_exact_alarm",
            "vibrate"
          ]

          [tool.flet.android.manifest_application]
          usesCleartextTraffic = "true"
          EOF
